# Site settings
title: Study Note
email: eunjikim@dm.snu.ac.kr
url: "http://ejklike.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
  - jemoji

# github_username:  ejklike
# description: "machine learning, statistical learning, pattern recognition, deep learning, data, datamining, data mining, data scientist, python, programming"
# baseurl: "" # the subpath of your site, e.g. /blog/
# kramdown:
  # input: GFM
  # syntax_highlighter: rouge

  # - jekyll-paginate
# paginate: 1
# paginate_path: "/page:num/"

# post:
#   template: _post.txt
#   extension: md

# page:
#   template: _page.txt
#   extension: md
# editor: gvim
# git:
#   branch: master
# transfer:
#   command: rsync
#   settings: -av
#   source: _site/
#   destination: ~/Git/username.github.com/