# Site settings
title: Eunji Kim @ CAU
author: Eunji Kim
description: 김은지 Eunji Kim, 중앙대학교 경영학부 조교수 Assistant Professor at School of Business Administration, Chung-Ang University
email_txt: eunjikim [at] cau.ac.kr
office_ko: 310관 1119호
office_en: Centennial Bldg (Bldg. 310) Room 1119
address_ko: 서울특별시 동작구 흑석로 84 중앙대학교 310관(100주년기념관) 1119호
address_en: 310-1119, 84, Heukseok-ro, Dongjak-gu, Seoul 06974, South Korea
scholar_url: https://scholar.google.co.kr/citations?user=uy3YrY8AAAAJ
cv_url: https://docs.google.com/document/d/1XifrmhkKUD4BLlRgSXUHuwWq6CbBirxhcry4Qoze_Qs/edit?usp=sharing
orcid_url: https://orcid.org/0000-0003-4857-521X
url: "http://ejklike.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
plugins: 
  - jemoji
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-feed # atom feed
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

include:
  - class
  - pages
exclude: [img]
