# Site settings
title: Eunji Kim @ CAU
author: Eunji Kim
email_txt: eunjikim [at] cau.ac.kr
office_ko: 310관 1119호
office_en: Centennial Bldg (Bldg. 310) Room 1119
address_ko: 서울특별시 동작구 흑석로 84 중앙대학교 310관(100주년기념관) 1119호
address_en: Room 1119, Bldg 310, 84, Heukseok-ro, Dongjak-gu, Seoul 06974, South Korea
url: "http://ejklike.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
gems:
  - jemoji
  - jekyll-email-protect
  - jekyll-github-metadata
sass:
  sass_dir: _sass
  style: compressed

exclude: [img]
